#!/usr/bin/env python3
"""Generate the small offline speech library used by Sunny Town.

The browser's speechSynthesis API is kept as a fallback, but it is not
dependable enough to be the primary voice on iOS.  These clips are generated
once, committed to public/audio, and then played with a regular <audio>
element.

Regenerate with:
    python3 -m pip install edge-tts==7.2.8
    python3 scripts/generate-speech.py
"""

from __future__ import annotations

import asyncio
import json
import re
from pathlib import Path

import edge_tts


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "public" / "audio"
MANIFEST = ROOT / "src" / "lib" / "speechClips.generated.ts"
OFFLINE_MANIFEST = OUTPUT / "manifest.json"
VOICE = "en-US-JennyNeural"
RATE = "-12%"

ANIMALS = {
    "Cow": "Moo!",
    "Pig": "Oink oink!",
    "Sheep": "Baa!",
    "Duck": "Quack quack!",
    "Cat": "Meow!",
    "Dog": "Woof woof!",
    "Horse": "Neigh!",
    "Chicken": "Cluck cluck!",
}
FOODS = [
    "Apple",
    "Banana",
    "Orange",
    "Strawberry",
    "Carrot",
    "Broccoli",
    "Cookie",
    "Grapes",
]
COLORS = ["Red", "Blue", "Yellow", "Green", "Orange", "Purple", "Pink", "Brown"]
SHAPES = ["Circle", "Square", "Triangle", "Star", "Heart"]
NUMBERS = [
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
    "Thirteen",
    "Fourteen",
    "Fifteen",
    "Sixteen",
    "Seventeen",
    "Eighteen",
    "Nineteen",
    "Twenty",
]
PLACES = [
    "The farm. Tap an animal!",
    "The kitchen. Feed Munchy!",
    "The paint tent. Pick a color!",
    "The balloons. Pop and count!",
    "The workshop. Match the shapes!",
    "The station. Build the train!",
]


def key(text: str) -> str:
    return " ".join(re.sub(r"[^a-z0-9 ]", "", text.lower()).split())


def slug(text: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", key(text)).strip("-")
    return value[:90]


def build_lines() -> list[str]:
    lines = {
        "Hello! Welcome to Sunny Town. Let's learn some words!",
        "Sound on",
        "Like this",
        "Yum!",
        "Yummy!",
        "Try again!",
        "Now you say it.",
        "Here comes another train! Find number one.",
        "Four! One, two, three, four! All aboard!",
        "The train is leaving the station! Goodbye!",
        *PLACES,
        *FOODS,
        *COLORS,
        *SHAPES,
        *NUMBERS,
    }

    for animal, sound in ANIMALS.items():
        lower = animal.lower()
        lines.update(
            {
                animal,
                sound,
                f"{animal}. Now you say it.",
                f"Touch the {lower}!",
                f"Not the {lower}!",
            }
        )

    for food in FOODS:
        lower = food.lower()
        lines.update(
            {
                f"Give me the {lower}!",
                f"Yummy, but I want the {lower}!",
            }
        )

    for color in COLORS:
        lower = color.lower()
        lines.update(
            {
                f"Find {lower}!",
                f"That is not {lower}.",
            }
        )

    for shape in SHAPES:
        lower = shape.lower()
        article = "an" if lower[0] in "aeiou" else "a"
        lines.update(
            {
                f"This is {article} {lower}.",
                f"That one is {article} {lower}.",
            }
        )

    return sorted(lines, key=key)


async def generate() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    entries: dict[str, str] = {}

    for index, text in enumerate(build_lines(), start=1):
        normalized = key(text)
        filename = f"{slug(text)}.mp3"
        destination = OUTPUT / filename
        entries[normalized] = f"/audio/{filename}"
        if not destination.exists():
            print(f"[{index:03}] {text}")
            await edge_tts.Communicate(
                text=text,
                voice=VOICE,
                rate=RATE,
            ).save(str(destination))

    source = (
        "/* Generated by scripts/generate-speech.py. Do not edit by hand. */\n"
        "export const SPEECH_CLIPS: Readonly<Record<string, string>> = "
        + json.dumps(entries, indent=2, ensure_ascii=False)
        + ";\n"
    )
    MANIFEST.write_text(source, encoding="utf-8")
    OFFLINE_MANIFEST.write_text(
        json.dumps(sorted(set(entries.values())), indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    asyncio.run(generate())
